name: Playwright + Cucumber BDD (with Allure)

on:
  push:
    branches: [ main ]            # avoid duplicate runs with PRs
  pull_request:
    branches: [ "*" ]
  schedule:
    # 18:30 IST daily (13:00 UTC)
    - cron: "0 13 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Prepare result dirs
        run: mkdir -p results allure-results

      # ---- Debug block (one run). This will surface the real reason if CI fails early.
      - name: Debug Cucumber
        run: |
          set -e
          node -v
          npm -v
          npx cucumber-js --version
          echo "== PWD ==" && pwd
          echo "== List features ==" && ls -R src/features || true

          echo "== Dry run: discover features (no execution) =="
          npx cucumber-js --config cucumber.cjs --dry-run --format progress --backtrace

          echo "== Real run: verbose output =="
          npx cucumber-js --config cucumber.cjs --format progress --backtrace
      # ---- End debug block

      - name: Generate Allure Report
        if: always()
        run: npx allure generate allure-results --clean

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Upload Allure HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Playwright Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-artifacts
          path: |
            playwright-report
            test-results
            traces
          if-no-files-found: ignore
